### ISSUE TITLE
no implicit conversion of nil into String

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/yus#2]
Trying to start-up yus on the new Server I get:
```
bin/yusd:14:in `join': no implicit conversion of nil into String (TypeError)
```
where is this coming from?

**Comment by zdavatz** [comment]
looking closer I get:
```
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/needle-1.3.0/lib/needle/definition-context.rb:36: warning: undefining `initialize' may cause serious problems
/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/needle-1.3.0/lib/needle/definition-context.rb:36: warning: undefining `object_id' may cause serious problems
/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/needle-1.3.0/lib/needle/definition-context.rb:36: warning: undefining `__send__' may cause serious problems
/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/ydbd-pg-0.5.6/lib/dbd/pg/database.rb:83:in `rescue in initialize': invalid connection option "tty" (DBI::OperationalError)
        from /home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/ydbd-pg-0.5.6/lib/dbd/pg/database.rb:40:in `initialize'
        from /home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/ydbd-pg-0.5.6/lib/dbd/Pg.rb:157:in `new'
        from /home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/ydbd-pg-0.5.6/lib/dbd/Pg.rb:157:in `connect'
        from /home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/ydbi-0.5.6/lib/dbi/handles/driver.rb:33:in `connect'
        from /home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/ydbi-0.5.6/lib/dbi.rb:148:in `connect'
        from /home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/odba-1.1.6/lib/odba/connection_pool.rb:63:in `block in _connect'
        from /home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/odba-1.1.6/lib/odba/connection_pool.rb:62:in `times'
        from /home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/odba-1.1.6/lib/odba/connection_pool.rb:62:in `_connect'
        from /home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/odba-1.1.6/lib/odba/connection_pool.rb:59:in `block in connect'
        from /home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/odba-1.1.6/lib/odba/connection_pool.rb:59:in `synchronize'
        from /home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/odba-1.1.6/lib/odba/connection_pool.rb:59:in `connect'
        from /home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/odba-1.1.6/lib/odba/connection_pool.rb:22:in `initialize'
        from bin/yusd:52:in `new'
        from bin/yusd:52:in `<main>'
/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/ydbd-pg-0.5.6/lib/dbd/pg/database.rb:52:in `initialize': invalid connection option "tty" (PG::ConnectionBad)
        from /home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/ydbd-pg-0.5.6/lib/dbd/pg/database.rb:52:in `new'
        from /home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/ydbd-pg-0.5.6/lib/dbd/pg/database.rb:52:in `initialize'
        from /home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/ydbd-pg-0.5.6/lib/dbd/Pg.rb:157:in `new'
        from /home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/ydbd-pg-0.5.6/lib/dbd/Pg.rb:157:in `connect'
        from /home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/ydbi-0.5.6/lib/dbi/handles/driver.rb:33:in `connect'
        from /home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/ydbi-0.5.6/lib/dbi.rb:148:in `connect'
        from /home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/odba-1.1.6/lib/odba/connection_pool.rb:63:in `block in _connect'
        from /home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/odba-1.1.6/lib/odba/connection_pool.rb:62:in `times'
        from /home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/odba-1.1.6/lib/odba/connection_pool.rb:62:in `_connect'
        from /home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/odba-1.1.6/lib/odba/connection_pool.rb:59:in `block in connect'
        from /home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/odba-1.1.6/lib/odba/connection_pool.rb:59:in `synchronize'
        from /home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/odba-1.1.6/lib/odba/connection_pool.rb:59:in `connect'
        from /home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/odba-1.1.6/lib/odba/connection_pool.rb:22:in `initialize'
        from bin/yusd:52:in `new'
        from bin/yusd:52:in `<main>'
```

**Comment by zdavatz** [comment]
fixed with: https://github.com/zdavatz/yus/commit/726f3b7af976e889823458e6a72fce17aef60dc9
